---
title: "Traffic Crashes EDA"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Hannah Ma"
date: today

format: 
  html:
   toc: true
   embed-resources: true
editor: source

execute:
  warning: false
  echo: false
---

An executive summary should summarize the key points of the report. It should restate the purpose of the report, highlight the major results, and summarize any conclusions. This report should be concise and clearly written.

::: {.callout-tip icon="false"}
## Github Repo and Data Source

<https://github.com/stat301-1-2023-fall/final-project-1-Hanyuyuu>

<https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if>
:::

## Project Overview

This exploratory data analysis (EDA) project investigates over 700,000 traffic crashes in Chicago using a high-quality dataset from the City of Chicago. The primary goal is to understand the landscape of traffic crashes in the city, addressing questions about predictors, causes, and patterns associated with these incidents. The analysis utilizes R and various packages for visualization and mapping.

## Key Findings

### At First Glance

The majority of reported traffic accidents do not result in injuries. Crashes often occur in clear weather, during daylight, and on dry roads. Primary causes include failing to yield, following too closely, and improper overtaking. Technology-related distractions contribute minimally to crashes.

-   Primary and secondary contributory causes of crashes are typically driver-dependent. Encouragingly, technology-related distractions have a relatively low impact on crash occurrences.

-   Crashes peak in the early afternoon, on Fridays, and during October. Data suggests increased traffic correlates with crash crash frequency.

### Looking Deeper

-   Driver-dependent causes contribute significantly to the number of injuries in crashes. Crashes involving pedestrians tend to result in more severe injuries.

-   Increase in weather-related crashes during winter months, despite fewer incidents overall. Certain weather conditions, like blowing snow and severe wind, show a higher likelihood of fatal crashes.

-   Substance abuse-related crashes occur disproportionately at night. Obscured vision crashes increase between 6-10 am.

-   Most crashes occur at around 30 mph, with outliers suggesting potential data collection errors. Relationship between the number of units involved in a crash and posted speed limit explored. Delay in Reporting Analysis:

-   Crashes often reported promptly, with peaks in reporting delay at whole-number units (days, weeks, years).

-   Clusters of crashes observed in West, downtown, and South Chicago regions. Discrepancies between mapped crashes and top recorded addresses warrant further investigation. 

## Conclusion
The analysis provides a comprehensive understanding of traffic crashes in Chicago, emphasizing the influence of driver behavior, weather conditions, and contributing causes. While most incidents are non-fatal, notable patterns emerge, such as the higher occurrence of substance-related crashes at night. The findings suggest opportunities for policy improvements to address specific challenges, such as reducing dangerous driving due to substance abuse.

## Future Directions 
Further investigation into regional clusters and addressing discrepancies between mapped and recorded crash locations could provide insights into road design flaws and enhance the effectiveness of safety measures. Additionally, addressing substance-related crashes at night may require targeted interventions and policy adjustments.

## References 
The project utilized the City of Chicago's Traffic Crashes dataset and mapping resources from Duke University's Center for Data & Visualization.
